ShowRegSys/Models/Dog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ShowRegSys.Models
{
    public class Dog
    {
        public int DogId { get; set; }

        [Required]
        [StringLength(100, MinimumLength=1)]
        [Display(Name = "Imię i przydomek")]
        public string Name { get; set; }

        [Display(Name="Numer PKR")]
        public string numerPKR { get; set; }
        
        public int PkrID { get; set; }

        [Required]
        [Display(Name = "Rasa")]
        public int BreedID { get; set; }

        [Display(Name = "Maść")]
        public int ColorID { get; set; }

        [Display(Name = "Rasa")]
        public int GenderID { get; set; }

        [Display(Name="Tatuaż lub chip")]
        public string TattooOrChip { get; set; }

        [Required]
        public int UserProfileId { get; set; }

        [Display(Name = "Hodowca")]
        public string Breeder { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Data urodzenia")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime BirthDate { get; set; }

        [Display(Name = "Tytuły")]
        public string Titles { get; set; }

        public virtual Pkr Pkr { get; set; }
        public virtual Breed Breed { get; set; }
        public virtual Color Color { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}

ShowRegSys/Controllers/DogController.cs
using System; 
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShowRegSys.Models;
using ShowRegSys.DAL;
using PagedList;
using System.Security;
using WebMatrix.WebData;
using System.Web.Security;
using ShowRegSys.Filters;
using ShowRegSys.ViewModels;
using System.Web.Script.Serialization;


namespace ShowRegSys.Controllers
{
    [Authorize]
    public class DogController : Controller
    {
        private ShowContext db = new ShowContext();

        //--------------------------------------
        //------------GET: /Dog/---------------
        //--------------------------------------
        [AllowAnonymous]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm 
                = String.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var dogs = db.Dogs.Include(d => d.Breed).Include(d => d.UserProfile);

            if (!String.IsNullOrEmpty(searchString))
            {
                dogs = dogs.Where(d => d.Name.ToUpper().Contains(searchString.ToUpper())
                    || d.Breed.Name.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "Name_desc":
                    dogs = dogs.OrderByDescending(d => d.Name);
                    break;
                default:
                    dogs = dogs.OrderBy(d => d.Name);
                    break;
            }
            
            int pageSize = 5;
            int pageNumber = ( page ?? 1);

            int zlicz = dogs.ToList().Count();

            if (zlicz > 0)
            {
                return View(dogs.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                return RedirectToAction("NoDog");
            }
        }

        //
        // GET: /Dog/Details/5

        [AllowAnonymous]
        public ActionResult Details( DogDetailsViewModel dogDetails, int? page, int id = 0)
        {

            Dog dog = db.Dogs.Find(id);

            if (dog == null)
            {
                return HttpNotFound();
            }

            var enrol = db.Enrollments.Where(e => e.DogID == dog.DogId).OrderBy(e => e.EnrollmentID);
            var pageIndex = dogDetails.Page ?? 1; //to samo co pageNumber
            int pageSize = 5;

            dogDetails.Name = dog.Name;
            dogDetails.numerPKR = dog.numerPKR;
            dogDetails.PkrName = dog.Pkr.Name;
            dogDetails.BreedName = dog.Breed.Name;
            dogDetails.ColorName = dog.Color.NamePL;
            dogDetails.GenderName = dog.Gender.NamePL;
            dogDetails.TattooOrChip = dog.TattooOrChip;
            dogDetails.Breeder = dog.Breeder;
            dogDetails.BirthDate = dog.BirthDate;
            dogDetails.Titles = dog.Titles;
            dogDetails.EnrollmentPagedList = enrol.ToPagedList(pageIndex, pageSize);

            return View(dogDetails);
        }

        //
        // GET: /Dog/Create

        public ActionResult Create()
        {
            DogCreateViewModel dog = new DogCreateViewModel();
            dog.UserProfileId = WebSecurity.GetUserId(User.Identity.Name);
            dog.GenderList = db.Genders.ToList().Select(u => new SelectListItem { Text = u.NamePL, Value = u.GenderID.ToString() }).ToList();
            dog.ColorList = db.Colors.ToList().Select(u => new SelectListItem { Text = u.NamePL, Value = u.ColorID.ToString() }).ToList();
            dog.PkrList = db.Pkrs.ToList().Select(u => new SelectListItem { Text = u.Name, Value = u.Name }).ToList();
            dog.BreedList = db.Breeds.ToList().Select(u => new SelectListItem { Text = u.Name, Value = u.BreedID.ToString() }).ToList();
            return View(dog);
        }

        //
        // POST: /Dog/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DogCreateViewModel dog)
        {
            if (ModelState.IsValid)
            {
                int getPkrID = (from m in db.Pkrs
                             where m.Name == dog.SelectedPkrValue
                             select m.PkrID).First();


                Dog newDog = new Dog()
                {
                    BirthDate = dog.BirthDate,
                    GenderID = dog.SelectedGenderFromList,
                    BreedID = dog.SelectedBreedFromList,
                    ColorID = dog.SelectedColorFromList,
                    DogId = dog.DogId,
                    Name = dog.Name,
                    numerPKR = dog.PkrNumber,
                    PkrID = getPkrID,
                    TattooOrChip = dog.TattooOrChip,
                    Titles = dog.Titles,
                    UserProfileId = dog.UserProfileId,
                    Breeder = dog.Breeder
                };

                db.Dogs.Add(newDog);
                db.SaveChanges();
                return RedirectToAction("MyDogs");
            }

            return View();
        }

        //
        // GET: /Dog/Edit/5

        public ActionResult Edit(int id = 0)
        {
           
            
            Dog dog = db.Dogs.Find(id);
            if (dog == null)
            {
                return HttpNotFound();
            }
            
            var userID = WebSecurity.GetUserId(User.Identity.Name);

            DogCreateViewModel dogEdit = new DogCreateViewModel()
            {
                DogId = dog.DogId,
                Name = dog.Name,
                PkrNumber = dog.numerPKR,
                SelectedBreedFromList = dog.BreedID,
                SelectedColorFromList = dog.ColorID,
                SelectedGenderFromList = dog.GenderID,
                TattooOrChip = dog.TattooOrChip,
                UserProfileId = userID,
                Breeder = dog.Breeder,
                BirthDate = dog.BirthDate,
                Titles = dog.Titles,
                SelectedPkrValue = dog.Pkr.Name
            };
            dogEdit.GenderList = db.Genders.ToList().Select(u => new SelectListItem { Text = u.NameEN, Value = u.GenderID.ToString() }).ToList();
            dogEdit.ColorList = db.Colors.ToList().Select(u => new SelectListItem { Text = u.NameEN, Value = u.ColorID.ToString() }).ToList();
            dogEdit.PkrList = db.Pkrs.ToList().Select(u => new SelectListItem { Text = u.Name, Value = u.Name }).ToList();
            dogEdit.BreedList = db.Breeds.ToList().Select(u => new SelectListItem { Text = u.Name, Value = u.BreedID.ToString() }).ToList();

            return View(dogEdit);
        }

        //
        // POST: /Dog/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DogCreateViewModel dogEdit)
        {
            var userID = WebSecurity.GetUserId(User.Identity.Name);

            if (ModelState.IsValid)
            {
                int getPkrID = (from m in db.Pkrs
                                where m.Name == dogEdit.SelectedPkrValue
                                select m.PkrID).First();

                Dog dogEdits = new Dog()
                {
                    BirthDate = dogEdit.BirthDate,
                    GenderID = dogEdit.SelectedGenderFromList,
                    BreedID = dogEdit.SelectedBreedFromList,
                    ColorID = dogEdit.SelectedColorFromList,
                    DogId = dogEdit.DogId,
                    Name = dogEdit.Name,
                    numerPKR = dogEdit.PkrNumber,
                    PkrID = getPkrID,
                    TattooOrChip = dogEdit.TattooOrChip,
                    Titles = dogEdit.Titles,
                    UserProfileId = dogEdit.UserProfileId,
                    Breeder = dogEdit.Breeder
                };
                

                db.Entry(dogEdits).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("MyDogs");
            }
            dogEdit.GenderList = db.Genders.ToList().Select(u => new SelectListItem { Text = u.NameEN, Value = u.GenderID.ToString() }).ToList();
            dogEdit.ColorList = db.Colors.ToList().Select(u => new SelectListItem { Text = u.NameEN, Value = u.ColorID.ToString() }).ToList();
            dogEdit.PkrList = db.Pkrs.ToList().Select(u => new SelectListItem { Text = u.Name, Value = u.Name }).ToList();
            dogEdit.BreedList = db.Breeds.ToList().Select(u => new SelectListItem { Text = u.Name, Value = u.BreedID.ToString() }).ToList();


            return View(dogEdit);

        }

        //
        // GET: /Dog/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Dog dog = db.Dogs.Find(id);
            if (dog == null)
            {
                return HttpNotFound();
            }
            return View(dog);
        }

        //
        // POST: /Dog/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Dog dog = db.Dogs.Find(id);
            var enrol = db.Enrollments.Where(e => e.DogID == dog.DogId).ToList();
            foreach (var item in enrol)
            {
                db.Enrollments.Remove(item);
                db.SaveChanges();
            }

            db.Dogs.Remove(dog);
            db.SaveChanges();
            return RedirectToAction("MyDogs");

ShowRegSys/Views/Dog/Create.cshtml
@model ShowRegSys.ViewModels.DogCreateViewModel

@{
    ViewBag.Title = "Dodawanie psa";
}

<h2>@ViewBag.Title</h2>
<br />
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Dog</legend>

        @Html.HiddenFor(m => m.DogId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.PkrNumber)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m => m.SelectedPkrValue, (IEnumerable<SelectListItem>)Model.PkrList, string.Empty)
            @Html.ValidationMessageFor(model => model.SelectedPkrValue)
            
            @Html.EditorFor(model => model.PkrNumber)
            @Html.ValidationMessageFor(model => model.PkrNumber)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.BreedList)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m => m.SelectedBreedFromList, (IEnumerable<SelectListItem>)Model.BreedList, string.Empty)
            @Html.ValidationMessageFor(model => model.SelectedBreedFromList)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ColorList)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m => m.SelectedColorFromList, (IEnumerable<SelectListItem>)Model.ColorList, String.Empty)
            @Html.ValidationMessageFor(model => model.SelectedColorFromList)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.GenderList)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m => m.SelectedGenderFromList, (IEnumerable<SelectListItem>)Model.GenderList, String.Empty)
            @Html.ValidationMessageFor(model => model.SelectedGenderFromList)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TattooOrChip)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TattooOrChip)
            @Html.ValidationMessageFor(model => model.TattooOrChip)
        </div>
        
        <div class="editor-label">
            @Html.Hidden("UserProfileId")
            @Html.ValidationMessageFor(model => model.UserProfileId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Breeder)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Breeder)
            @Html.ValidationMessageFor(model => model.Breeder)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.BirthDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BirthDate)
            @Html.ValidationMessageFor(model => model.BirthDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Titles)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Titles)
            @Html.ValidationMessageFor(model => model.Titles)
        </div>

        <p>
            <input type="submit" value="Dodaj" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Powrót do listy psów", "MyDogs")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(document).ready(function () {
            $("#SelectedPkrValue").change(function () {
                $('#SelectedBreedFromList > option').remove();

                $.ajax({
                    url: '@Url.Action("GetProperBreeds")',
                    data: { pkrName: $(this).val() },
                    cache: false,
                    dateType: "json",
                    type: "POST",
                    error: function() {
                        alert("An error occurred.");
                    },
                    success: function (data) {
                        var items = "";
                        $.each(data, function(i, item)
                        {
                            items += "<option value=\"" + item.Value + "\">" + item.Text + "</option>";
                        });
                        
                        $("#SelectedBreedFromList").html(items);
                    }
                });
            });
        });
    </script>
}

ShowRegSys/Views/Dog/Delete.cshtml
@model ShowRegSys.Models.Dog

@{
    ViewBag.Title = "Usuń psa";
}

<h2>@ViewBag.Title</h2>

<h3>Czy na pewno chcesz usunąć następującego psa?</h3>
<br />

<fieldset>
    <legend>Dog</legend>

    <div class="display-label">
         <b>@Html.DisplayNameFor(model => model.Name)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         <b>@Html.DisplayNameFor(model => model.Breed.Name)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Breed.Name)
    </div>

    <div class="display-label">
        <b>Właściciel</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>

    <div class="display-label">
        <b>@Html.DisplayNameFor(model => model.BirthDate)</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BirthDate)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Usuń" /> |
        @Html.ActionLink("Powróć do listy psów", "MyDogs")
    </p>
}

ShowRegSys/Views/Dog/Details.cshtml
@model ShowRegSys.ViewModels.DogDetailsViewModel
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Details";
}

<h2>Informacje szczegółowe</h2>
<fieldset>
    <legend>Dog</legend>
    <table>
        <tr>
            <td>
                <b>@Html.DisplayNameFor(model => model.Name)</b>
            </td>
            <td>
                @Html.DisplayFor(model => model.Name)
            </td>
        </tr>
        <tr>
            <td>
                <b>@Html.DisplayNameFor(model => model.numerPKR)</b>
            </td>
            <td>
                @Html.DisplayFor(model => model.PkrName)-
                @Html.DisplayFor(model => model.numerPKR)
            </td>
        </tr>
        <tr>
            <td>
                <b>@Html.DisplayNameFor(model => model.BreedName)</b>
            </td>
            <td>
                @Html.DisplayFor(model => model.BreedName)
            </td>
        </tr>
        <tr>
            <td>
                <b>@Html.DisplayNameFor(model => model.ColorName)</b>
            </td>
            <td>
                @Html.DisplayFor(model => model.ColorName)
            </td>
        </tr>
        <tr>
            <td>
                <b>@Html.DisplayNameFor(model => model.GenderName)</b>
            </td>
            <td>
                @Html.DisplayFor(model => model.GenderName)
            </td>
        </tr>
        <tr>
            <td>
                <b>@Html.DisplayNameFor(model => model.TattooOrChip)</b>
            </td>
            <td>
                @Html.DisplayFor(model => model.TattooOrChip)
            </td>
        </tr>
       @* <tr>
            <td>
                <b>@Html.DisplayNameFor( model => model.UserProfile.UserName)</b>
            </td>
            <td>
                @Html.DisplayFor(model => model.UserProfile.UserName)
            </td>
        </tr>*@
        <tr>
            <td>
                <b>@Html.DisplayNameFor(model => model.Breeder)</b>
            </td>
            <td>
                @Html.DisplayFor(model => model.Breeder)
            </td>
        </tr>
        <tr>
            <td>
                <b>@Html.DisplayNameFor(model => model.BirthDate)</b>
            </td>
            <td>
                @Html.DisplayFor(model => model.BirthDate)
            </td>
        </tr>
    </table>

    <div class="display-field">
        <table>
            <tr>
                <th>Zgłoszony na:</th>
            </tr>
            <tr>
                <td>
                    <b>Wystawa</b>
                </td>
                <td>
                    <b>Klasa</b>
                </td>
            </tr>


            @foreach (var enrol in Model.EnrollmentPagedList)
            {
                <tr>
                    <td>
                        @enrol.Shows.Name
                    </td>
                    <td>
                        @enrol.Classes.NamePL
                    </td>
                </tr>

            }
        </table>
    </div>
    <br />

    Strona @(Model.EnrollmentPagedList.PageCount < Model.EnrollmentPagedList.PageNumber ? 0 : Model.EnrollmentPagedList.PageNumber) z @Model.EnrollmentPagedList.PageCount 
         
    @Html.PagedListPager( Model.EnrollmentPagedList, 
            page => Url.Action("Details", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }) )


    

</fieldset>
<p>
    @Html.ActionLink("Wróc do listy psów", "Index")
</p>

ShowRegSys/Views/Dog/Edit.cshtml
@model ShowRegSys.ViewModels.DogCreateViewModel

@{
    ViewBag.Title = "Edytowanie psa";
}

<h2>@ViewBag.Title</h2>
<br />
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Dog</legend>

        @Html.HiddenFor(model => model.DogId)
        @Html.Hidden("UserProfileId")


        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        
        <div class="editor-ladel">
            @Html.LabelFor(model => model.PkrNumber)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.SelectedPkrValue, (IEnumerable<SelectListItem>)Model.PkrList)
            @Html.ValidationMessageFor(model => model.SelectedPkrValue)

            @Html.EditorFor(model => model.PkrNumber)
            @Html.ValidationMessageFor(model => model.PkrNumber)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.BreedList)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m => m.SelectedBreedFromList, (IEnumerable<SelectListItem>)Model.BreedList)
            @Html.ValidationMessageFor(model => model.BreedList)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.ColorList)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m => m.SelectedColorFromList, (IEnumerable<SelectListItem>)Model.ColorList)
            @Html.ValidationMessageFor(model => model.ColorList)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.GenderList)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m => m.SelectedGenderFromList, (IEnumerable<SelectListItem>)Model.GenderList)
            @Html.ValidationMessageFor(model => model.SelectedGenderFromList)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.TattooOrChip)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TattooOrChip)
            @Html.ValidationMessageFor(model => model.TattooOrChip)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Breeder)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Breeder)
            @Html.ValidationMessageFor(model => model.Breeder)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.BirthDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BirthDate)
            @Html.ValidationMessageFor(model => model.BirthDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Titles)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Titles)
            @Html.ValidationMessageFor(model => model.Titles)
        </div>

        <p>
            <input type="submit" value="Zapisz" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Powrót do listy psów", "MyDogs")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(document).ready(function () {
            $("#SelectedPkrValue").change(function () {
                $('#SelectedBreedFromList > option').remove();

                $.ajax({
                    url: '@Url.Action("GetProperBreeds")',
                    data: { pkrName: $(this).val() },
                    cache: false,
                    dateType: "json",
                    type: "POST",
                    error: function() {
                        alert("An error occurred.");
                    },
                    success: function (data) {
                        var items = "";
                        $.each(data, function(i, item)
                        {
                            items += "<option value=\"" + item.Value + "\">" + item.Text + "</option>";
                        });
                        
                        $("#SelectedBreedFromList").html(items);
                    }
                });
            });
        });
    </script>
}


ShowRegSys/Views/Dog/Index.cshtml
@model PagedList.IPagedList<ShowRegSys.Models.Dog>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@{
    ViewBag.Title = "Psy";
}

<h2>@ViewBag.Title</h2>

@using(Html.BeginForm("Index", "Dog", FormMethod.Get))
{
    <p>
        Znajdź psa po imieniu lub rasie @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Szukaj" />
    </p>
}
<table>
    <tr>
        <th>
            @Html.ActionLink("Imię i przydomek", "Index", new { sortOrder = ViewBag.NameSortParm})
        </th>
        <th>
            Rasa
        </th>
        <th>
            Właściciel
        </th>
        <th>
            Data urodzenia
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Breed.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserProfile.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BirthDate)
        </td>
        <td>
            @Html.ActionLink("Szczegóły", "Details", new { id=item.DogId })
        </td>
    </tr>
}

</table>
<br />

Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) z @Model.PageCount

@Html.PagedListPager( Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }) )

ShowRegSys/Views/Dog/Moje.cshtml
@model IEnumerable<ShowRegSys.Models.Dog>

@{
    ViewBag.Title = "Moje Psy";
}

<h2>@ViewBag.Title</h2>
<p>
    @Html.ActionLink("Dodaj psa", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Breed.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserProfile.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthDate)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Breed.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserProfile.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BirthDate)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "Edit", new { id=item.DogId }) |
            @Html.ActionLink("Szczegóły", "Details", new { id=item.DogId }) |
            @Html.ActionLink("Usuń", "Delete", new { id=item.DogId })
        </td>
    </tr>
    }
</table>

ShowRegSys/Views/Dog/MyDogs.cshtml
@model IEnumerable<ShowRegSys.Models.Dog>

@{
    ViewBag.Title = "Moje Psy";
}

<h2>@ViewBag.Title</h2>
<p>
    @Html.ActionLink("Dodaj psa", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Breed.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserProfile.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthDate)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Breed.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserProfile.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BirthDate)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "Edit", new { id=item.DogId }) |
            @Html.ActionLink("Usuń", "Delete", new { id=item.DogId })
        </td>
    </tr>
    }
</table>

ShowRegSys/Views/Dog/NoDog.cshtml
@model IEnumerable<ShowRegSys.Models.Dog>

@{
    ViewBag.Title = "Brak psów w bazie";
}

<h2>@ViewBag.Title</h2>

<h3>Obecnie w bazie niema żadnego psa. </h3>
<h4>@Html.ActionLink("Dodaj swojego psa", "Create")</h4>   