ShowRegSys/Controllers/RegController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShowRegSys.Models;
using ShowRegSys.DAL;
using System.Security;
using WebMatrix.WebData;
using System.Web.Security;
using ShowRegSys.Filters;
using ShowRegSys.ViewModels;

namespace ShowRegSys.Controllers
{
    [Authorize]
    public class RegController : Controller
    {
        private ShowContext db = new ShowContext();


        public ActionResult Index()
        {
            /*DogDropDownList();*/


            return View();
        }

        //GET
        public ActionResult Create()
        {
            EnrollmentCreateViewModel enrol = new EnrollmentCreateViewModel();

            var userIDb = WebSecurity.GetUserId(User.Identity.Name);
            var userIDa = Convert.ToInt32(userIDb);

            enrol.ShowList = db.Shows.ToList().Where(b => b.Date > DateTime.Now).Select(s => new SelectListItem { Text = s.Name, Value = s.ShowID.ToString() }).ToList();
            enrol.DogList = db.Dogs.ToList().Where(b => b.UserProfile.UserProfileId == userIDa).Select(d => new SelectListItem { Text = d.Name, Value = d.DogId.ToString() }).ToList();
            enrol.ClassList = db.Classes.ToList().Select(c => new SelectListItem { Text = c.NamePL, Value = c.ClassID.ToString() }).ToList();

            return View(enrol);

        }

        //POST:
        [HttpPost]
        public ActionResult Create(EnrollmentCreateViewModel enrol)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var allElrollments = db.Enrollments;

                    foreach(var item in allElrollments)
                    {
                        if(item.DogID == enrol.SelectedDogFromList & item.ShowID == enrol.SelectedShowFromList)
                        {
                            return RedirectToAction("DogRegistred");
                        }
                    }


                    Enrollment newEnrol = new Enrollment()
                    {
                        ShowID = enrol.SelectedShowFromList,
                        DogID = enrol.SelectedDogFromList,
                        ClassID = enrol.SelectedClassFromList
                    };
                    db.Enrollments.Add(newEnrol);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                    
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unadle to save chandes.");
            }
            return View();
        }


        public ActionResult DogRegistred()
        {
            return View();
        }
    }
}

ShowRegSys/Views/Reg/Create.cshtml
@model ShowRegSys.ViewModels.EnrollmentCreateViewModel

@{
    ViewBag.Title = "Zgłoszenie psa na wystawę";
}

<h2>Złoszenie psa na wystawę</h2>
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
        
    <fieldset>
        <legend>Enrollment</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.ShowList)
        </div>
        <div class="editor-label">
            @Html.DropDownListFor(model => model.SelectedShowFromList, (IEnumerable<SelectListItem>)Model.ShowList, string.Empty)
            @Html.ValidationMessageFor(m => m.ShowList)
        </div>

        <div class="editor-field">
            @Html.LabelFor(model => model.DogList)
        </div>
        <div class="editor-label">
            @Html.DropDownListFor(model => model.SelectedDogFromList, (IEnumerable<SelectListItem>)Model.DogList, string.Empty)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ClassList)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.SelectedClassFromList, (IEnumerable<SelectListItem>)Model.ClassList, string.Empty)
        </div>
        <p>
            <input type="submit" value="Zgłoś" />
        </p>
    </fieldset>
}

ShowRegSys/Views/Reg/DogRegistred.cshtml
@{
    ViewBag.Title = "DogRegistred";
}

<h1>Pies został już zgłoszony na tą wystawę!</h1>
<h3>@Html.ActionLink("Nowe złoszenie", "Create", "Reg")</h3>

ShowRegSys/Views/Reg/Index.cshtml
@{
    ViewBag.Title = "Zgłoszenie przyjęte";
}

<h2>Zgłoszenie przyjęte</h2>
Pies został zgłoszny na wystawę.