ShowRegSys/Models/Show.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ShowRegSys.Models
{
    public class Show
    {
        public int ShowID { get; set; }

        [Required]
        [Display(Name = "Nazwa")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Miasto")]
        public string City { get; set; }

        [Required]
        [Display(Name = "Miejsce wystawy")]
        public string Place { get; set; }
        
        [Required]
        [Display(Name = "Data")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        [Required]
        [Display(Name = "Ranga")]
        public int RankID { get; set; }

        [Required]
        [Display(Name = "Uwagi")]
        public string Attention { get; set; }

        [Required]
        [Display(Name = "Data zgłoszeń")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime EnrollmentDate { get; set; }

        [Required]
        public int OrganizerID { get; set; }

        public virtual Rank Rank { get; set; }
        public virtual Organizer Organizer { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual ICollection<Image> Images { get; set; }
    }
}

ShowRegSys/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShowRegSys.Models;
using ShowRegSys.DAL;

namespace ShowRegSys.Controllers
{
    [Authorize]
    public class CatalogController : Controller
    {
        private ShowContext db = new ShowContext();

        //
        // GET: /Catalog/

        public ActionResult Index( int id = 0)
        {
            Show show = db.Shows.Find(id);

            if (show == null)
            {
                return HttpNotFound();
            }


            return View(show);
        }

    }
}

ShowRegSys/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShowRegSys.Models;
using ShowRegSys.DAL;
using PagedList;

namespace ShowRegSys.Controllers
{
    public class ImageController : Controller
    {
        private ShowContext db = new ShowContext();

        //
        // GET: /Image/

        public ActionResult Index()
        {
            return View();
        }
        //
        // GET: upload
        public ActionResult Upload(int showID)
        {
            ViewBag.showID = showID;
            return View();
        }


        //
        // POST: Upload
        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file, int showID, string imageName)
        {
            try
            {
                if(file.ContentLength >0)
                {

                    ViewBag.showID = showID;
                    var fileName = Path.GetFileName(file.FileName);
                    var path1 = Path.Combine(Server.MapPath("~/Images"), fileName);
                    var path2 = string.Format("/Images/{0}", fileName);
                    file.SaveAs(path1);

                    Image image = new Image();
                    image.Path = path2;
                    image.Name = imageName;
                    image.ShowId = showID;

                    db.Images.Add(image);
                    db.SaveChanges();
                }
                ViewBag.Message = "Przesyłanie zakończone.";
                return View("AddDone");
            }
            catch (Exception e)
            {
                throw;
                ViewBag.Message = "Przesyłanie przerwane";
                return RedirectToAction("Index");
            }
        }

        public ActionResult AddDone(int showID)
        {
            ViewBag.ShowID = showID;
            return View();
        }

        //
        //GET /ImageList/5
        public ActionResult ImageList(int showID)
        {
            var images = db.Images.Where(s => s.ShowId == showID).OrderBy(s => s.ImageId);
            var show = db.Shows.Find(showID);
            ViewBag.ShowName = show.Name;
            ViewBag.ShowId = show.ShowID;
            return View(images.ToList());
        }


        //
        //POST /ImageList/5
        public ActionResult SingleImage(int imageId, int showId)
        {
            var images = db.Images.Where(s => s.ShowId == showId).OrderBy(s => s.ImageId).ToArray();
            ViewBag.CurrentImageId = imageId;
            ViewBag.CurrentShowId = showId;

            var nextImg = images.FirstOrDefault(i => i.ImageId > imageId);
            if(nextImg == null)
            {
                ViewBag.NextImageId = imageId;
            }
            else
            {
                int nextId = nextImg.ImageId;
                ViewBag.NextImageId = nextId;
            }

            var prevImg = images.LastOrDefault(i => i.ImageId < imageId);
            if(prevImg == null)
            {
                ViewBag.PrevImageId = imageId;
            }
            else
            {
                int prevId = prevImg.ImageId;
                ViewBag.PrevImageId = prevId;
            }
            
            var image = db.Images.Find(imageId);
            return View(image);
        }


        //
        //GET /Image/ImageAdmin/5
        public ActionResult ImageAdmin(int? page, int id = 0)
        {
            var images = db.Images.Where(s => s.ShowId == id).OrderBy(s => s.ImageId);
            var show = db.Shows.Find(id);
            ViewBag.ShowName = show.Name;
            ViewBag.ShowId = show.ShowID;

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            int zlicz = images.ToList().Count();

            if(zlicz > 0)
            {
                return View(images.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                return RedirectToAction("NoImage");
            }
            
            
            return View(images.ToList());
        }

        //
        //GET Image/Delete/5
        public ActionResult Delete(int id = 0, int showId = 0)
        {
            Image image = db.Images.Find(id);
            if( image == null )
            {
                return HttpNotFound();
            }
            ViewBag.ShowId = showId;
            return View(image);
        }

        //
        //POST /Image/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int showId)
        {
            Image image = db.Images.Find(id);
            db.Images.Remove(image);
            db.SaveChanges();
            string path = image.Path;
            System.IO.File.Delete(Path.GetFullPath(AppDomain.CurrentDomain.BaseDirectory + Path.Combine(Server.MapPath("~/Images"), path)));


            return RedirectToAction("ImageAdmin", new { showID = showId });
        }
    }
}

ShowRegSys/Controllers/ShowController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShowRegSys.Models;
using ShowRegSys.DAL;
using ShowRegSys.Filters;
using System.Web.Security;
using WebMatrix.WebData;
using ShowRegSys.ViewModels;
using PagedList;

namespace ShowRegSys.Controllers
{  
    [Authorize]
    [InitializeSimpleMembership]
    public class ShowController : Controller
    {
        private ShowContext db = new ShowContext();
        private UsersContext dbUser = new UsersContext();

        //
        // GET: /Show/

        public ActionResult Index()
        {
            var shows = db.Shows.Include(o => o.Organizer).Include(r => r.Rank);

            return View(shows.ToList());
        }

        public ActionResult MyShows()
        {
            int userId = WebSecurity.GetUserId(User.Identity.Name);

            var getOrgId = (from u in dbUser.UserProfiles
                            where u.UserProfileId == userId
                            select u.OrganizerID).First();

            int getOrganizerId = Convert.ToInt16(getOrgId);

            var shows = db.Shows.Include(s => s.Organizer).Include(r => r.Rank).Where(d => d.Date >= DateTime.Now && d.OrganizerID == getOrganizerId);

            return View(shows.ToList());

        }

        //
        // GET: /Show/Details/5

        public ActionResult Details(ShowDetailsViewModel showDetails, int? page, string sortOrder, string currentFilter, string searchString, int id = 0)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm
                = String.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";

            if (searchString != null)
            {
                showDetails.Page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            Show show = db.Shows.Find(id);
            if (show == null)
            {
                return HttpNotFound();
            }

            var enrol = db.Enrollments.Where(e => e.ShowID == show.ShowID);


            if (!String.IsNullOrEmpty(searchString))
            {
                enrol = enrol.Where(e => e.Dogs.Breed.Name.ToUpper().Contains(searchString.ToUpper()));
                    
            }

            switch (sortOrder)
            {
                case "Name_desc":
                    enrol = enrol.OrderByDescending(e => e.Classes.NamePL);
                    break;
                default:
                    enrol = enrol.OrderBy(e => e.Classes.NamePL);
                    break;
            }

            var pageIndex = showDetails.Page ?? 1;
            int pageSize = 10;

            showDetails.ShowId = show.ShowID;
            showDetails.Name = show.Name;
            showDetails.City = show.City;
            showDetails.Place = show.Place;
            showDetails.Date = show.Date;
            showDetails.RankName = show.Rank.Name;
            showDetails.Attention = show.Attention;
            showDetails.EnrollmentDate = show.EnrollmentDate;
            showDetails.OrganizerName = show.Organizer.Name;
            showDetails.OrganizerTel = show.Organizer.Telephone;
            showDetails.OrganizerEmail = show.Organizer.Email;
            showDetails.OrganizerBankAccount = show.Organizer.BankAccount;
            showDetails.OrganizerWww = show.Organizer.WebAdress;
            showDetails.EnrollmentList = enrol.ToPagedList(pageIndex, pageSize);

            return View(showDetails);
        }

        //
        // GET: /Show/Catalog/5
        public ActionResult Catalog(int id = 0)
        {

            Show show = db.Shows.Find(id);
            if (show == null)
            {
                return HttpNotFound();
            }

            var enrol = db.Enrollments.Where(e => e.ShowID == show.ShowID);
            int orgID = show.OrganizerID;
            Organizer organizer = db.Organizers.Find(orgID);

            ShowCatalogDetailsViewModel enrolments = new ShowCatalogDetailsViewModel();
            enrolments.ShowId = show.ShowID;
            enrolments.ShowName = show.Name;
            enrolments.City = show.City;
            enrolments.Place = show.Place;
            enrolments.Date = show.Date;
            enrolments.Rank = show.Rank.Name;
            enrolments.OrganizerName = organizer.Name;
            enrolments.Telephone = organizer.Telephone;
            enrolments.Email = organizer.Email;
            enrolments.BankAccount = organizer.BankAccount;
            enrolments.WebAddress = organizer.WebAdress;
            enrolments.Attention = show.Attention;
            enrolments.EnrolList = db.Enrollments.Where(e => e.ShowID == show.ShowID).OrderBy(e => e.Dogs.PkrID).ThenBy(e => e.Dogs.Breed.Name).ThenBy(e => e.Classes.ClassID).ToList();



            return View(enrolments);
        }

        //
        // GET: /Show/Create
        [Authorize(Roles = "Organizer")]
        public ActionResult Create()
        {
            int userId = WebSecurity.GetUserId(User.Identity.Name);

            int getOrgId = Convert.ToInt16((from u in dbUser.UserProfiles
                            where u.UserProfileId == userId
                            select u.OrganizerID).First());


            ShowCreateEditViewModel show = new ShowCreateEditViewModel();
            show.OrganizerID = getOrgId;
            show.RankList = db.Ranks.ToList().Select(r => new SelectListItem { Text = r.Name, Value = r.RankID.ToString() }).ToList();
            
            return View(show);
        }

        //
        // POST: /Show/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ShowCreateEditViewModel show)
        {
            if (ModelState.IsValid)
            {
                int userId = WebSecurity.GetUserId(User.Identity.Name);
                
                int getOrgId = Convert.ToInt16((from u in dbUser.UserProfiles
                            where u.UserProfileId == userId
                            select u.OrganizerID).First());

                Show newShow = new Show()
                {
                    Name = show.Name,
                    City = show.City,
                    Place = show.Place,
                    Date = show.Date,
                    RankID = show.SelectedRankFromList,
                    Attention = show.Attention,
                    EnrollmentDate = show.EnrollmentDate,
                    OrganizerID = getOrgId
                };
                show.RankList = db.Ranks.ToList().Select(r => new SelectListItem { Text = r.Name, Value = r.RankID.ToString() }).ToList();
                
                    db.Shows.Add(newShow);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Show/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Show show = db.Shows.Find(id);
            if (show == null)
            {
                return View("NoShow");
            }

            ShowCreateEditViewModel editShow = new ShowCreateEditViewModel()
            {
                ShowID = show.ShowID,
                Name = show.Name,
                City = show.City,
                Place = show.Place,
                Date = show.Date,
                SelectedRankFromList = show.RankID,
                Attention = show.Attention,
                EnrollmentDate = show.EnrollmentDate,
                OrganizerID = show.OrganizerID
            };
            editShow.RankList = db.Ranks.ToList().Select(r => new SelectListItem { Text = r.Name, Value = r.RankID.ToString() }).ToList();

            return View(editShow);
        }

        //
        // POST: /Show/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ShowCreateEditViewModel editShow)
        {
            if (ModelState.IsValid)
            {
                Show show = db.Shows.Find(editShow.ShowID);
                
                show.Name = editShow.Name;
                show.City = editShow.City;
                show.Place = editShow.Place;
                show.Date = editShow.Date;
                show.RankID = editShow.SelectedRankFromList;
                show.Attention = editShow.Attention;
                show.EnrollmentDate = editShow.EnrollmentDate;
                show.OrganizerID = editShow.OrganizerID;
                

                db.Entry(show).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("MyShows");
            }

            editShow.RankList = db.Ranks.ToList().Select(r => new SelectListItem { Text = r.Name, Value = r.RankID.ToString() }).ToList();
            return View(editShow);
        }

        //
        // GET: /Show/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Show show = db.Shows.Find(id);
            if (show == null)
            {   
                return HttpNotFound();
            }
            return View(show);
        }

        //
        // POST: /Show/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Show show = db.Shows.Find(id);
            var enrol = db.Enrollments.Where(e => e.ShowID == show.ShowID).ToList();
            foreach(var item in enrol)
            {
                db.Enrollments.Remove(item);
                db.SaveChanges();
            }


ShowRegSys/Views/Show/Catalog.cshtml
@model ShowRegSys.ViewModels.ShowCatalogDetailsViewModel
@{
    ViewBag.Title = "Details";
}
<p>
    @Html.ActionLink("Powrót do listy wystaw", "MyShows")
</p>

<h2>Katalog:</h2>
<table>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.ShowName)</b></td>
        <td>@Html.DisplayFor(model => model.ShowName)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.City)</b></td>
        <td>@Html.DisplayFor(model => model.City)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.Place)</b></td>
        <td>@Html.DisplayFor(model => model.Place)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.Date)</b></td>
        <td>@Html.DisplayFor(model => model.Date)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.Rank)</b></td>
        <td>@Html.DisplayFor(model => model.Rank)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.OrganizerName)</b></td>
        <td>@Html.DisplayFor(model => model.OrganizerName)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.Telephone)</b></td>
        <td>@Html.DisplayFor(model => model.Telephone)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.Email)</b></td>
        <td>@Html.DisplayFor(model => model.Email)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.BankAccount)</b></td>
        <td>@Html.DisplayFor(model => model.BankAccount)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.WebAddress)</b></td>
        <td>@Html.DisplayFor(model => model.WebAddress)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.Attention)</b></td>
        <td>@Html.DisplayFor(model => model.Attention)</td>
    </tr>
</table>


<h3>Zgłoszone psy:</h3>
<table>
    <tr>
        <td><b>Numer psa</b></td>
        <td><b>Grupa</b></td>
        <td><b>Imie i przydomek</b></td>
        <td><b>Rasa</b></td>
        <td><b>Klasa</b></td>
    </tr>
    @{
        int i = 1;
    }
    
    @foreach (var enrol in Model.EnrolList)
    {
        <tr>
            <td>@i</td>
            <td>@enrol.Dogs.PkrID</td>
            <td>@enrol.Dogs.Name</td>
            <td>@enrol.Dogs.Breed.Name</td>
            <td>@enrol.Classes.NamePL</td>
        </tr>
        i = i + 1;
    }

</table>

<p>
    @Html.ActionLink("Powrót do listy wystaw", "MyShows")
</p>

ShowRegSys/Views/Show/Create.cshtml
@model ShowRegSys.ViewModels.ShowCreateEditViewModel
@{
    ViewBag.Title = "Nowa wystawa";
}

<h2>@ViewBag.Title</h2>
<br />

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Show</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.City)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.City)
            @Html.ValidationMessageFor(model => model.City)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Place)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Place)
            @Html.ValidationMessageFor(model => model.Place)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Date)
            @Html.ValidationMessageFor(model => model.Date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RankList)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m => m.SelectedRankFromList, (IEnumerable<SelectListItem>)Model.RankList, string.Empty)
            @Html.ValidationMessageFor(model => model.SelectedRankFromList)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Attention)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Attention)
            @Html.ValidationMessageFor(model => model.Attention)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EnrollmentDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EnrollmentDate)
            @Html.ValidationMessageFor(model => model.EnrollmentDate)
        </div>
        <p>
            <input type="submit" value="Dodaj" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Powrót do listy wystaw", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ShowRegSys/Views/Show/Delete.cshtml
@model ShowRegSys.Models.Show

@{
    ViewBag.Title = "Usuń wystawę";
}

<h2>@ViewBag.Title</h2>

<h3>Czy na pewno chcesz usunąć tą wystawę?</h3>
<table>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.Name):</b></td>
        <td>@Html.DisplayFor(model => model.Name)</td>
    </tr>
</table>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Usuń" /> |
        @Html.ActionLink("Powrót do listy wystaw", "Index")
    </p>
}

ShowRegSys/Views/Show/Details.cshtml
@model ShowRegSys.ViewModels.ShowDetailsViewModel
@using PagedList.Mvc
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Szczegóły wystawy";
}

<h2>@ViewBag.Title</h2>

<table>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.Name)    </b></td>
        <td>@Html.DisplayFor(model => model.Name)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.City)    </b></td>
        <td>@Html.DisplayFor(model => model.City)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.Place)    </b></td>
        <td>@Html.DisplayFor(model => model.Place)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.Date):</b></td>
        <td>@Html.DisplayFor(model => model.Date)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.RankName):</b></td>
        <td>@Html.DisplayFor(model => model.RankName)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.OrganizerName):</b></td>
        <td>@Html.DisplayFor(model => model.OrganizerName)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.OrganizerTel)</b></td>
        <td>@Html.DisplayFor(model => model.OrganizerTel)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.OrganizerEmail):</b></td>
        <td>@Html.DisplayFor(model => model.OrganizerEmail)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.OrganizerBankAccount):</b></td>
        <td>@Html.DisplayFor(model => model.OrganizerBankAccount)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.OrganizerWww)    </b></td>
        <td>@Html.DisplayFor(model => model.OrganizerWww)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.Attention)    </b></td>
        <td>@Html.DisplayFor(model => model.Attention)</td>
    </tr>
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.EnrollmentDate)    </b></td>
        <td>@Html.DisplayFor(model => model.EnrollmentDate)</td>
    </tr>
</table>
<h3>@Html.ActionLink("Dodaj zdjęcie", "Upload", "Image", new { showID = Model.ShowId }, null )</h3>

@using (Html.BeginForm("Details", "Show", FormMethod.Get))
{
    <p>
        Znajdź psy po rasie @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Szukaj" />
    </p>
}

    <div class="display-field">
        <table>
            <tr>
                <th>
                    <b>Zgłoszone psy:</b>
                </th>
            </tr>
            <tr>
                <td>
                   <b>Imię i przydomek</b>
                </td>
                <td>
                    <b>Rasa</b>
                </td>
                <td>
                    <b>@Html.ActionLink("Klasa", "Details", new {sortOrder = ViewBag.NameSortParm})</b>
                </td>
            </tr>
            @foreach(var enrol in Model.EnrollmentList)
            {

                <tr>
                    <td>
                        @enrol.Dogs.Name
                    </td>
                    <td>
                        @enrol.Dogs.Breed.Name
                    </td>
                    <td>
                        @enrol.Classes.NamePL
                    </td>
                </tr>
            }

        </table>
    </div>
Strona @(Model.EnrollmentList.PageCount < Model.EnrollmentList.PageNumber ? 0 : Model.EnrollmentList.PageNumber) z @Model.EnrollmentList.PageCount

@Html.PagedListPager(Model.EnrollmentList,
            page => Url.Action("Details", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))



    
<p>
    @Html.ActionLink("Powrót do listy wystaw", "Index")
</p>

ShowRegSys/Views/Show/Index.cshtml
@model IEnumerable<ShowRegSys.Models.Show>

@{
    ViewBag.Title = "Wystawy";
}

<h2>@ViewBag.Title</h2>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            Ranga
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Organizer.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rank.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Organizer.Name)
        </td>
        <td>
            @Html.ActionLink("Szczegóły", "Details", new { id=item.ShowID }) |
            @Html.ActionLink("Galeria", "ImageList", "Image", new { showID = item.ShowID }, null) 
        </td>
    </tr>
}

</table>

ShowRegSys/Views/Show/MyShows.cshtml
@model IEnumerable<ShowRegSys.Models.Show>

@{
    ViewBag.Title = "Moje wystawy";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Dodaj wystawę", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            Ranga
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Organizer.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rank.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Organizer.Name)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "Edit", new { id=item.ShowID }) |
            @Html.ActionLink("Szczegóły", "Details", new { id=item.ShowID }) |
            @Html.ActionLink("Usuń", "Delete", new { id=item.ShowID }) |
            @Html.ActionLink("Zdjęcia", "ImageAdmin", "Image", new { id = item.ShowID }, null) |
            @Html.ActionLink("Katalog", "Catalog", new { id = item.ShowID })
        </td>
    </tr>   
}

</table>

ShowRegSys/Views/Show/NoShow.cshtml
@{
    ViewBag.Title = "Brak wystaw w bazie";
}

<h2>@ViewBag.Title</h2>

<h3>Obecnie w bazie niema żadnej wystawy. </h3>
<h4>@Html.ActionLink("Dodaj wystawę", "Create")</h4>   